### ISSUE TITLE
Introduce a lazy loading and code splitting for routes

### ISSUE THREAD

**Issue by pziemkowski** [apptension/react-scripts-apptension#20]

**Comment by mikeqcp** [comment]
Options we have:

- https://github.com/jamiebuilds/react-loadable 
Most GH stars, but not maintained any more and it is not compatible with Webpack v4+ and Babel v7+

- https://reactjs.org/docs/code-splitting.html#reactlazy (+ Suspense)
Native React solution, but it doesnt support SSR yet

- https://loadable-components.com/
Most complete solution right now, recommended by React team (for cases where SSR is needed). Seems to cover all cases from Lazy + Suspense, and adds SSR support on top of that
