### ISSUE TITLE
Research and implement mockit support

### ISSUE THREAD

**Issue by pziemkowski** [apptension/react-scripts-apptension#29]

**Comment by mikeqcp** [comment]
The biggest drawback of [mockIt](https://mockit.netlify.com/) I see is that you can't share the endpoint configuration between developers - as far as I understand it is configured locally and cannot be pushed to repo in an readable way.

What about using [json-server](https://github.com/typicode/json-server)? It creates a full REST API (with GET/POST/PUT requests for both single items and collections) based on single json config file (which can be pushed on repo). And additionaly it seems to provide quite a lot custom options for customization if needed

@pziemkowski @iraminius What do you think? Do you have any preference?

**Comment by mortigen** [comment]
We can go with json-server. It will be easier to maintain and share in team
