### ISSUE TITLE
Cleanup the repository

### ISSUE THREAD

**Issue by mikeqcp** [apptension/react-scripts-apptension#53]
Since CRA@3.3.0 was introduced and we can just use template instead of whole scripts, this repository needs a cleanup.

- [ ] rename from `react-scripts-apptension` to `cra-template-apptension`
- [ ] it's not the fork from `facebook/create-react-app` anymore - we should remove the fork history and keep it as a separate repo just with our template
- [ ] for the same reason (because its a fork) there are some version tags already used, so whenever we use a new version in package.json (currenlty `1.1.2` we can't tag the commit, because the original repo already uses higher versions and the tags are already used

**Comment by mortigen** [comment]
As far as I know there isn't any easy option to "unfork" repo. We can either write to support and wait or just create new repo.

**Comment by pziemkowski** [comment]
Let's create a new repo and upload the code there

**Comment by mikeqcp** [comment]
Moved over to https://github.com/apptension/cra-template-apptension
